train_pkl: /path/to/AU_training_seq.pkl
test_pkl: /path/to/AU_val_seq.pkl
final_test_pkl: "/path/to/AU_val_image.pkl"

train_img_path: /path/to/train_image_path
test_img_path: /path/to/test_image_path
n_segment: 100
train_audio_path: /path/to/AU_training_audio_fea.pkl
test_audio_path: /path/to/AU_val_audio_fea.pkl
audio_fea_dim: 896

use_audio_fea: False

task: "AU"
dataset_type: "AU_training_BLB"
stage1_checkpoint: /path/to/stage1_checkpoint


hidden_size: [256,128,64]  

lr: 0.00005
momentum: 0.9
weight_decay: 0.00001
batch_size: 32
optim: "AdamW"

num_epochs: 50
num_works: 36
ema_interval: 1
ema_ratio: 0.001
use_ema: False
resume: null 

start_epoch: 0
print_freq: 20
save_epoch: 1
accum_iter: 100
use_dp: True
device: [0,1]

log_dir: "./logs"
checkpoint_dir: "./checkpoints/"
weights: [5.278187667237907, 12.42675934708439, 3.9182460964352357, 2.3713836486482838, 1.5735074526534674, 1.8198100142634426, 2.586578383618721, 22.66022149366239, 20.121237822349574, 22.104986149584487, 1.0, 8.264810560409762]

